#' Plot Monthly spells
#'
#' @param obsstats output generated by get_observed_statistics 
#' @param simstats output generated by get_simulated_statistics
#' @param fig_dir  Directory to create PDF containing the plot. Can be NULL to plot on screen
#' @param filename  filename of PDF to create, containing the plot. The .pdf ending is added in the function, not needed in the filename. Default is 2_BasinWide_Trials_MonthlySpells. 
#' @param vars, variables default is c("prcp","tmax","tmin")
#' @param spells, default is c("wet","dry")  TODO: The package uses dry, wet, extreme check if we should switch defaults to c('d', 'w', 'e')
#' @export
#' @examples
#' plot_basinwide_spells_monthly(obsstats, simstats)
#' 
#'
plot_basinwide_spells_monthly <- function(obsstats, simstats, fig_dir=NULL, filename="2_BasinWide_Trials_MonthlySpells", vars=c("prcp","tmax","tmin", "wind"), spells=c("wet","dry")){
  stats <- c("mean","stdev","skew")
  months <- c(1:12)
  if(!is.null(fig_dir)){
    pdf(width=3*length(spells), height=3*length(stats), file=file.path(fig_dir, paste0(filename,".pdf")))
  }
  layout(matrix(1:(length(spells)*length(stats)), ncol=length(spells), nrow=length(stats), byrow=FALSE))
  
  for(iv in 1:length(spells)){
    for(is in seq_along(stats)){
      x <- simstats[-1, 1, (iv - 1) * 2 + is, months]
      y <- obsstats[-1, 1, (iv - 1) * 2 + is, months]
      ylim <- c(min(x, y, na.rm = TRUE), max(x, y, na.rm = TRUE))
      boxplot(x, ylim=ylim, xlab=ifelse(is == length(stats), "Months", ""), ylab=ifelse(iv == 1, paste(stats[is], "(days)"), ""), main=ifelse(is == 1, spells[iv], ""))
      points(1:12, y, col="red")
    }
  }
  legend(x="bottom", legend=c("Observations", "Simulated trials"), pch=19, col=c("red", "black"))
  if(!is.null(fig_dir)){
    dev.off()
  }
}