#' Plot annual extremes
#'
#' @param obsstats output generated by get_observed_statistics 
#' @param simstats output generated by get_simulated_statistics
#' @param fig_dir  Directory to create PDF containing the plot. Can be NULL to plot on screen
#' @param filename  filename of PDF to create, containing the plot. The .pdf ending is added in the function, not needed in the filename. Default is 3_BasinWide_Trials_AnnualExtremeEvents.pdf 
#' @param stats, default is c("mean","stdev","skew")
#' @param vars, variables default is c("prcp","tmax","tmin")
#' @param months, month numbers, default is c(1:12)
#' @export
#' @examples
#' plot_basinwide_extreme_annual(obsstats, simstats)
#' 
#'
plot_basinwide_extreme_annual <- function(obsstats, simstats, fig_dir=NULL, filename="3_BasinWide_Trials_AnnualExtremeEvents", vars=c("prcp","tmax","tmin"), return.periods=c(10,30,100)){
  if(!is.null(fig_dir)){
    pdf(width=3*length(vars), height=3*1, file=file.path(fig_dir, paste0(filename, ".pdf")))
  }
  layout(matrix(1:(length(vars)*1), ncol=length(vars), nrow=1, byrow=FALSE))
  
  for(iv in seq_along(vars)){
    x <- simstats[-1, 1, iv, ]
    y <- obsstats[-1, 1, iv, ]
    ylim <- c(min(x, y, na.rm = TRUE), max(x, y, na.rm = TRUE))
    boxplot(x, ylim=ylim, xlab="Return period (years)", ylab=vars[iv])
    points(1:length(return.periods), y, col="red")
  }
  legend(x="bottom", legend=c("Observations", "Simulated trials"), pch=19, col=c("red", "black"))
  if(!is.null(fig_dir)){
    dev.off()
  }
}