#' Plot sitespecific variables
#'
#' @param obsstats output generated by get_observed_statistics 
#' @param simstats output generated by get_simulated_statistics
#' @param fig_dir  Directory to create PDF containing the plot. Can be NULL to plot on screen
#' @param filename  filename of PDF to create, containing the plot. The .pdf ending is added in the function, not needed in the filename. Default is 4_Sites_MedianTrials_%timestep%_variables.pdf 
#' @param timestep timesteps to be plotted
#' @param stats, default is c("mean","stdev","skew")
#' @param vars, variables default is c("prcp","tmax","tmin")
#' @param months, month numbers, default is c(1:12)
#' @export
#' @examples
#' for(it in seq_along(timesteps <- c("daily","monthly", "annual"))[-2]) try(plot_sitespecific_vars(obsstats, sim=mysimstats,timestep=timesteps[it]))
#' 
#' 
#'
plot_sitespecific_vars <- function(obsstats, simstats, fig_dir=NULL,  filename="4_Sites_MedianTrials_", timestep="daily", stats=c("mean","stdev","skew"), vars=c("prcp","tmax","tmin"), months=c(1:12)){
  timestep <- match.arg(timestep, timesteps)
  it <- switch(timestep, daily=1, monthly=2, annual=3)
  months <- switch(timestep, daily=1:12, monthly=1:12, annual=1)
  if(!is.null(fig_dir)){
    pdf(width=3*length(vars), height=3*length(stats), file=file.path(fig_dir, paste0(filename, timestep, "Variables", ".pdf")))
  }
  layout(matrix(1:(length(vars)*length(stats)),length(vars),length(stats),byrow=FALSE))
  
  for(iv in seq_along(vars)){
    for(is in seq_along(stats)){
      y <- as.vector(simstats[1, -1, is, iv, it, months])
      x <- as.vector(obsstats[1, -1, is, iv, it, months])
      xlim <- ylim <- c(min(x, y, na.rm = TRUE), max(x, y, na.rm = TRUE))
      plot(x, y, xlim=xlim, ylim=ylim, xlab="Observed", ylab="Simulated", main=paste(timestep, stats[is], vars[iv]))
      abline(0,1)
    }
  }
  if(!is.null(fig_dir)){
    dev.off()
  }
}