#' Plot Monthly variables
#'
#' @param obsstats output generated by get_observed_statistics 
#' @param simstats output generated by get_simulated_statistics
#' @param fig_dir  Directory to create PDF containing the plot. Can be NULL to plot on screen
#' @param filename  filename of PDF to create, containing the plot. The .pdf ending of the filename is added in the function. Default filename is 1_BasinWide_Trials_MonthlyVariables
#' @param stats, default is c("mean","stdev","skew")
#' @param vars, variables default is c("prcp","tmax","tmin")
#' @param months, month numbers, set to c(1:12)
#' @export
#' @examples
#' plot_basinwide_vars_monthly(obsstats, simstats)
#' 
#'
plot_basinwide_vars_monthly <- function(obsstats, simstats, fig_dir=NULL, filename="1_BasinWide_Trials_MonthlyVariables", stats=c("mean","stdev","skew"), vars=c("prcp","tmax","tmin"), months=c(1:12)){
  if(!is.null(fig_dir)){
    pdf(width=3*length(vars), height=3*length(stats), file=file.path(fig_dir, paste0(filename, ".pdf")))
  }
  layout(matrix(1:(length(vars)*length(stats)), ncol=length(vars), nrow=length(stats), byrow=FALSE))
  for(iv in seq_along(vars)){
    for(is in seq_along(stats)){
      x <- simstats[-1, 1, is, iv, 1, months]
      y <- obsstats[-1, 1, is, iv, 1, months]
      ylim <- c(min(x, y, na.rm = TRUE), max(x, y, na.rm = TRUE))
      boxplot(x, ylim=ylim, xlab=ifelse(is == length(stats), "Months", ""), ylab=ifelse(iv == 1, stats[is], ""), main=ifelse(is == 1, vars[iv], ""))
      points(1:12, y, col="red")
    }
  }
  legend(x="bottom", legend=c("Observations", "Simulated trials"), pch=19, col=c("red", "black"))
  if(!is.null(fig_dir)){
    dev.off()
  }
}